#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Call My Server

on: 
   push:
     branches:
       - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        run:
          echo "kaishi"
          ls
          echo "aaa" >> a.txt 
          echo "jieshu"

      - name: Test SSH Connection
        uses: easingthemes/ssh-deploy@main
        if: env.SSH_PRIVATE_KEY && ! contains(github.event.action, 'noser')
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr"
          SOURCE: a.txt
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: jun
          TARGET: "/www/wwwroot/tmp/"
